#ifndef HELLO_PADULAB_H
#define HELLO_PADULAB_H

/* Some cross-platform definitions generated by autotools */
#if HAVE_CONFIG_H
#  include <config.h>
#endif /* HAVE_CONFIG_H */

#endif /* HELLO_PADULAB_H */